## Regularization
To reduce overfitting and underfitting  we have three methods:   
        *a. Regularization    
        b. Boosting   
        c. Bagging*    

Let us look at regularization only for now.   


**Regularization** : Reduce Overfitting and Variance   

3 types of Regularization:   
    &nbsp; &nbsp;a. L1:LASSO Regression      
    &nbsp; &nbsp;b. L2:Ridge Regression  
    &nbsp; &nbsp;c. Combining L1 and L2: Elastic Net   
    

-- In Least square, we minimize RSS to find $\beta_{0}$  and  $\beta{1}$ intercept and slope.    

   
-- In Ridge Regression   
    we minimize $\sum_{i=1}^{n}(y_i - \beta_{0} - \sum_{j=1}^{p}\beta_{j}x_{ij})^2 + \lambda\sum_{j=1}^{p}\beta_{j}^{2} = RSS + \lambda\sum_{j=1}^{p}\beta_{j}^{2}$    
    
to find coeffs. 2nd term is called as Ridge penalty.   

-- In Lasso Regression   
    we minimize $\sum_{i=1}^{n}(y_i - \beta_{0} - \sum_{j=1}^{p}\beta_{j}x_{ij})^2 + \lambda\sum_{j=1}^{p}|\beta_{j}| = RSS + \lambda\sum_{j=1}^{p}|\beta_{j}|$      
    
 to find coeffs. 2nd term is called as Lasso penalty.

-- In Elastic Net Regression   
    we minimize $\sum_{i=1}^{n}(y_i - \beta_{0} - \sum_{j=1}^{p}\beta_{j}x_{ij})^2 + \lambda_{1}\sum_{j=1}^{p}\beta_{j}^{2} + \lambda_{2}\sum_{j=1}^{p}|\beta_{j}| = RSS + \lambda_{1}\sum_{j=1}^{p}\beta_{j}^{2} + \lambda_{2}\sum_{j=1}^{p}|\beta_{j}|$    
    
Alternatively, we can express it as:   
## $\frac{\sum_{i=1}^{n}(y_i - x_i^J\hat{\beta})^2}{2n} + \lambda( \frac{1-\alpha}{2}\sum_{j=1}^{m}\hat{\beta_j^2} + \alpha\sum_{j=1}^{m}|\hat{\beta_j}| )$   
$\alpha$ is a weightage for L1 and L2.   

## Data Setup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.drop('sales',  axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
poly_features.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [11]:
X_train.shape

(140, 19)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
#scales values on standardization or normalization
scaler = StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
scaled_X_train = scaler.transform(X_train)

In [16]:
scaled_X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([1.93200000e+02, 1.84000000e+01, 6.57000000e+01, 3.73262400e+04,
       3.55488000e+03, 1.26932400e+04, 3.38560000e+02, 1.20888000e+03,
       4.31649000e+03, 7.21142957e+06, 6.86802816e+05, 2.45233397e+06,
       6.54097920e+04, 2.33555616e+05, 8.33945868e+05, 6.22950400e+03,
       2.22433920e+04, 7.94234160e+04, 2.83593393e+05])

In [18]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

we can see scaled values are small, due to standardization

## 1. Ridge Regression

In [19]:
from sklearn.linear_model import Ridge

In [20]:
#help(Ridge)

In [21]:
#Here we take alpha=10, but we don't know if it is best value.
#here lambda is alpha
#So we have to do iterations and cross-validate for best alpha.
ridge_model = Ridge(alpha=10)

In [22]:
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [23]:
test_predictions = ridge_model.predict(scaled_X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5774404204714175

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.8946386461319681

### To know the best alpha | lamba value

In [27]:
#To get the best possible value for lambda or alpha, we use RidgeCV
#CV=cross validation.
from sklearn.linear_model import RidgeCV

In [28]:
#Checks for only this alphas (0.1,1.0,10.0)
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0))

In [29]:
ridge_cv_model.fit(scaled_X_train, y_train)    #in CV scaled_x_train is further split as train and test, hold.

RidgeCV(alphas=array([ 0.1,  1. , 10. ]))

In [30]:
# gives the best alpha
ridge_cv_model.alpha_

0.1

In [31]:
from sklearn.metrics import SCORERS

In [32]:
#metrics we can find in scorers
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [33]:
# we will put scorer and do the steps again
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring= 'neg_mean_absolute_error')

Chooses best alpha which gives highest negative mean_absolute_error.   
One can change the scorer metric to others in order to choose best alpha.   

In [34]:
ridge_cv_model.fit(scaled_X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [35]:
ridge_cv_model.alpha_

0.1

In [36]:
# test predictions, and see
test_predictions = ridge_cv_model.predict(scaled_X_test)

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.42737748843414897

In [39]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.6180719926948917

In [40]:
# to know coeffs
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

we see none of the coeffs in Ridge are zero.   
In Lasso it coeffs can go all the way to zero.  

--------------------

## 2. Lasso Regression   
    LASSO = Least absolute shrinkage and selecting operator
 https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html    
 https://scikit-learn.org/stable/modules/linear_model.html#lasso

In Lasso coefficients can be forced to be zero if lambda is sufficiently large.   
i.e., making few variables not contributing (selecting variables in other words).   

In [41]:
# selecting alpha beforehand, we use this ->
# from sklearn.linear_model import Lasso
# lasso_model = Lasso(alpha=10)
# lasso_model.fit(scaled_X_train, y_train)
# test_predictions
# find error

LassoCV is little different from RidgeCV, check the links. 

In [42]:
from sklearn.linear_model import LassoCV

In [43]:
lasso_cv_model = LassoCV(eps=.001, n_alphas=100, cv=5)

In [44]:
lasso_cv_model.fit(scaled_X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.8704406680899979, tolerance: 0.3684261714285714
  model = cd_fast.enet_coordinate_descent(


LassoCV(cv=5)

Did not converge warning.  i.e, stochastic search for alpha has not converged.

In [45]:
# we can reduce eps, decrease the widening between alpha_min and alpha_max to converge 
# eps = alpha_min/alpha_max
lasso_cv_model = LassoCV(eps=.1, n_alphas=100, cv=5, max_iter=1000)

In [46]:
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [47]:
lasso_cv_model.alpha_

0.4943070909225828

In [48]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [49]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.6541723161252856

In [50]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

1.1308001022762535

In [51]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

It has made lot of coeffs zero.   
Easy to interpret, only two variables here.   
Need Domain expertise to say RMSE is acceptable.

In [52]:
# increase max_iter to 10000, to have convergence. default is 1000.
lasso_cv_model = LassoCV(eps=.001, n_alphas=100, cv=5, max_iter=100000)

In [53]:
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(cv=5, max_iter=100000)

In [54]:
lasso_cv_model.alpha_

0.004943070909225827

In [55]:
test_predictions = lasso_cv_model.predict(scaled_X_test)

In [56]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4335034618590069

In [57]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

0.6063140748984026

In [58]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

We see model has become complex.   
Hard to interpret.   
Need to know which method to use to have convergence of alpha.  

## 3. Elastic Net   

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNetCV.html

In [59]:
from sklearn.linear_model import ElasticNetCV

In [61]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [62]:
elastic_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [65]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [66]:
# best l1_ratio
elastic_model.l1_ratio_

1.0

it chooses only lasso and completely discards ridge. May be due to the simple dataset we have taken.

In [67]:
elastic_model.alpha_

0.004943070909225827

this alpha is the same we got in Lasso.

In [68]:
lasso_cv_model.alpha_

0.004943070909225827

In [69]:
test_predictions = elastic_model.predict(scaled_X_test)

In [70]:
MAE = mean_absolute_error(test_predictions, y_test)
MAE

0.4335034618590069

In [71]:
RMSE = np.sqrt(mean_squared_error(test_predictions, y_test))
RMSE

0.6063140748984026

---------------